---
name: ポート／機器設定の日程調整
description: ポート／機器設定の依頼テンプレート
labels: [ポート／機器設定依頼]
body:
- type: checkboxes
  id: cat-preferences
  attributes:
    label: What kinds of cats do you like?
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: Black cat
